taxi/urls.py
from django.urls import path

from .views import (
    index,
    CarListView,
    CarDetailView,
    DriverListView,
    DriverDetailView,
    ManufacturerListView,
    CarCreateView,
    CarUpdateView,
    CarDeleteView,
    ManufacturerCreateView,
    ManufacturerUpdateView,
    ManufacturerDeleteView,
    DriverCreateView,
    DriverDeleteView,
    DriverUpdateView,
    DriverLicenceUpdateView,
)

urlpatterns = [
    path("", index, name="index"),

    path("cars/", CarListView.as_view(), name="car-list"),
    path("cars/<int:pk>/", CarDetailView.as_view(), name="car-detail"),
    path("cars/create/", CarCreateView.as_view(), name="car-create"),
    path("cars/<int:pk>/update/", CarUpdateView.as_view(), name="car-update"),
    path("cars/<int:pk>/delete/", CarDeleteView.as_view(), name="car-delete"),

    path("manufacturers/", ManufacturerListView.as_view(), name="manufacturer-list"),
    path("manufacturers/create/", ManufacturerCreateView.as_view(), name="manufacturer-create"),
    path("manufacturers/<int:pk>/update/", ManufacturerUpdateView.as_view(), name="manufacturer-update"),
    path("manufacturers/<int:pk>/delete/", ManufacturerDeleteView.as_view(), name="manufacturer-delete"),

    path("drivers/", DriverListView.as_view(), name="driver-list"),
    path("drivers/<int:pk>/", DriverDetailView.as_view(), name="driver-detail"),
    path("drivers/create/", DriverCreateView.as_view(), name="driver-create"),
    path("drivers/<int:pk>/delete/", DriverDeleteView.as_view(), name="driver-delete"),
    path("drivers/<int:pk>/update/", DriverUpdateView.as_view(), name="driver-update"),
    path("drivers/<int:pk>/update/license-number", DriverLicenceUpdateView.as_view(), name="driver-license-update")
]

app_name = "taxi"

taxi_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("taxi.urls", namespace="taxi")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taxi/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Manufacturer(models.Model):
    name = models.CharField(max_length=255)
    country = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} {self.country}"


class Driver(AbstractUser):
    license_number = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = "driver"
        verbose_name_plural = "drivers"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("taxi:driver-detail", kwargs={'pk': self.pk})


class Car(models.Model):
    model = models.CharField(max_length=255)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    drivers = models.ManyToManyField(Driver, related_name="cars")

    def __str__(self):
        return self.model

taxi/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django import forms

from taxi.models import Driver


class DriverCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Driver
        fields = UserCreationForm.Meta.fields + ("license_number",
                                                 "first_name",
                                                 "last_name")

    def clean_license_number(self):
        license_number = self.cleaned_data["license_number"]

        if len(license_number) != 8:
            raise ValidationError("Number should consist 8 characters")

        if not license_number[:3].isupper() or not license_number[:3].isalpha():
            raise ValidationError("First 3 characters must be uppercase letters")

        if not license_number[3:].isdigit():
            raise ValidationError("Last 5 characters must be digits")

        return license_number


class CarSearchForm(forms.Form):
    title = forms.CharField(
        max_length=15,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by model..."})
    )

taxi/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import DriverCreationForm, CarSearchForm
from .models import Driver, Car, Manufacturer


def index(request):
    """View function for the home page of the site."""

    num_drivers = Driver.objects.count()
    num_cars = Car.objects.count()
    num_manufacturers = Manufacturer.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_drivers": num_drivers,
        "num_cars": num_cars,
        "num_manufacturers": num_manufacturers,
        "num_visits": num_visits + 1,
    }

    return render(request, "taxi/index.html", context=context)


class ManufacturerListView(generic.ListView):
    model = Manufacturer
    context_object_name = "manufacturer_list"
    template_name = "taxi/manufacturer_list.html"
    paginate_by = 5


class ManufacturerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Manufacturer
    fields = "__all__"
    success_url = reverse_lazy("taxi:manufacturer-list")
    template_name = "taxi/manufacturer_form.html"


class ManufacturerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Manufacturer
    fields = "__all__"
    success_url = reverse_lazy("taxi:manufacturer-list")
    template_name = "taxi/manufacturer_form.html"


class ManufacturerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Manufacturer
    success_url = reverse_lazy("taxi:manufacturer-list")
    template_name = "taxi/manufacturer_confirm_delete.html"


class CarListView(generic.ListView):
    model = Car
    queryset = Car.objects.all().select_related("manufacturer")
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CarListView, self).get_context_data(**kwargs)
        context["search_form"] = CarSearchForm()
        return context

    def get_queryset(self):
        model = self.request.GET.get("title")
        if model:
            return self.queryset.filter(model__icontains=model)
        return self.queryset


class CarDetailView(LoginRequiredMixin, generic.DetailView):
    model = Car


class CarCreateView(LoginRequiredMixin, generic.CreateView):
    model = Car
    fields = "__all__"
    success_url = reverse_lazy("taxi:car-list")


class CarUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Car
    fields = "__all__"
    success_url = reverse_lazy("taxi:car-list")
    template_name = "taxi/car_form.html"


class CarDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Car
    success_url = reverse_lazy("taxi:car-list")
    template_name = "taxi/car_confirm_delete.html"


class DriverListView(generic.ListView):
    model = Driver
    paginate_by = 5


class DriverDetailView(LoginRequiredMixin, generic.DetailView):
    model = Driver
    queryset = Driver.objects.all().prefetch_related("cars__manufacturer")


class DriverCreateView(LoginRequiredMixin, generic.CreateView):
    model = Driver
    form_class = DriverCreationForm


class DriverDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Driver
    success_url = reverse_lazy("taxi:driver-list")
    template_name = "taxi/driver_confirm_delete.html"


class DriverUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Driver
    form_class = DriverCreationForm
    success_url = reverse_lazy("taxi:driver-list")


class DriverLicenceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Driver
    success_url = reverse_lazy("taxi:driver-list")
    fields = "license_number",
    template_name = "taxi/driver_licence_update.html"

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Taxi Service</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link"> < </a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link"> > </a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
    <li class="list-group-item"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
  {% endif %}

  <br>

  <li class="list-group-item"><a href="{% url 'taxi:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'taxi:driver-list' %}">All drivers</a></li>
  <li class="list-group-item"><a href="{% url 'taxi:car-list' %}">All cars</a></li>
  <li class="list-group-item"><a href="{% url 'taxi:manufacturer-list' %}">All manufacturers</a></li>
</ul>

templates/taxi/car_confirm_delete.html
{% extends "base.html"%}

{% block content %}
  <h1>Delete car</h1>
  <p>Are you sure you want to delete car {{ car.model }}?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
  </form>
{% endblock %}

templates/taxi/car_detail.html
{% extends "base.html" %}

{% block content %}
    <h2>Car {{ car.id }} information:</h2>
    <p>Manufacturer: {{ car.manufacturer.name }}, {{ car.manufacturer.country }}</p>
        <p>
            <a href="{% url "taxi:car-update" pk=car.id %}"><button class="btn btn-secondary">Update</button></a>
            <a href="{% url "taxi:car-delete" pk=car.id %}"><button class="btn btn-secondary">Delete</button></a>
        </p>
    <h3>Drivers</h3>
    <hr>
    <ul>
    {% for driver in car.drivers.all %}
        <li>{{ driver.username }} ({{ driver.first_name }} {{ driver.last_name }})</li>
    {% endfor %}
    </ul>
{% endblock %}

templates/taxi/car_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>{{ object|yesno:"Update,Create" }} Car</h1>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

templates/taxi/car_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>
        Car list
        <a class="btn btn-primary adding" href="{% url "taxi:car-create" %}" role="button">Create</a>
    </h1>

    <form action="" method="get" class="form-inline">
        {{ search_form|crispy }}
        <input class="btn btn-secondary" type="submit" value="Find">
    </form>
    <br>
    {% if car_list %}
        <table class="table">
        <tr>
            <th>ID</th>
            <th>Model</th>
            <th>Manufacturer</th>
        </tr>
        {% for car in car_list %}
        <tr>
            <td><a href="{% url "taxi:car-detail" pk=car.id %}">{{ car.id }}</a></td>
            <td>{{ car.model }}</td>
            <td>{{ car.manufacturer }}</td>
        </tr>
        {% endfor %}
        </table>
    {% else %}
        <p>There are no cars in taxi yet :(</p>
    {% endif %}
{% endblock %}

templates/taxi/driver_confirm_delete.html
{% extends "base.html"%}

{% block content %}
  <h1>Delete driver</h1>
  <p>Are you sure you want to delete {{ driver.name }}?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
  </form>
{% endblock %}

templates/taxi/driver_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ driver.username }}
  </h1>
    <a href="{% url "taxi:driver-update" pk=driver.id%}"><button class="btn btn-secondary">Update</button></a>
    <a href="{% url "taxi:driver-delete" pk=driver.id%}"><button class="btn btn-secondary">Delete</button></a>

  <p><strong>First name:</strong> {{ driver.first_name }}</p>
  <p><strong>Last name:</strong> {{ driver.last_name }}</p>
  <p><strong>License number:</strong> {{ driver.license_number }}
    <a href="{% url 'taxi:driver-license-update' pk=driver.id %}">Update</a>
  </p>
  <p><strong>Is staff:</strong> {{ driver.is_staff }}</p>

  <div class="ml-3">
    <h4>Cars</h4>

    {% for car in driver.cars.all %}
        <hr>
        <p><strong>Model:</strong> {{ car.model }}</p>
        <p><strong>Manufacturer:</strong> {{ car.manufacturer.name }}</p>
        <p class="text-muted"><strong>Id:</strong> {{car.id}}</p>

    {% empty %}
      <p>No cars!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/taxi/driver_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create Driver</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/taxi/driver_licence_update.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Update License</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/taxi/driver_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
        Driver List
        <a class="btn btn-primary adding" href="{% url "taxi:driver-create" %}" role="button">Create</a>
    </h1>
    {% if driver_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>License number</th>
      </tr>
    {% for driver in driver_list %}
      <tr>
        <td>{{ driver.id }}</td>
        <td><a href="{{ driver.get_absolute_url }}">{{ driver.username }} {% if user == driver %} (Me){% endif %}</a></td>
        <td>{{ driver.first_name }}</td>
        <td>{{ driver.last_name }}</td>
        <td>{{ driver.license_number }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no drivers in the service yet :(</p>
    {% endif %}
{% endblock %}

templates/taxi/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Taxi Service Home</h1>
    <p>Welcome to Best Taxi Ever!</p>
    <h2>Dynamic content</h2>
    <p>The Taxi service has the following record counts:</p>
    <ul>
        <li><strong>Cars:</strong> {{ num_cars }}</li>
        <li><strong>Drivers:</strong> {{ num_drivers }}</li>
        <li><strong>Manufacturers:</strong> {{ num_manufacturers }}</li>
    </ul>

    <p>You have visited this page
        {{ num_visits }} time{{ num_visits|pluralize }}.
    </p>

{% endblock %}

templates/taxi/manufacturer_confirm_delete.html
{% extends "base.html"%}

{% block content %}
  <h1>Delete car</h1>

  <p>Are you sure you want to delete manufacturer {{ manufacturer.name }}?</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete, please" class="btn btn-danger">
  </form>
{% endblock %}

templates/taxi/manufacturer_form.html
{% extends "base.html" %}

{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Manufacturer</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/taxi/manufacturer_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
        Manufacturer List
        <a class="btn btn-primary adding" href="{% url "taxi:manufacturer-create" %}" role="button">Create</a>
    </h1>
    {% if manufacturer_list %}
      <table class="table">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Country</th>
        </tr>

        {% for manufacturer in manufacturer_list %}
            <tr>
              <td>
                  {{ manufacturer.id }}
              </td>
              <td>
                  {{ manufacturer.name }}
              </td>
              <td>
                  {{ manufacturer.country }}
              </td>
          </tr>
        {% endfor %}
      </table>
    {% else %}
        <p>There are no manufacturers in the service yet :(</p>
    {% endif %}
{% endblock %}